ATDL/ATDL/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('password/', include('password.urls')),
    path('macBellLaPadula/', include('macBellLaPadula.urls')),
]

ATDL/password/urls.py
from django.urls import path
from . import views
from django.conf.urls import static
import os
from django.conf import settings
urlpatterns = [
    path('', views.index, name='index'),
    path('checkAnderson', views.checkAnderson, name='checkAnderson'),
    path('requestLogin', views.userRequest, name='requestLogin'),
    path('challengeResponse',views.challengeResponse, name = 'challengeResponse'),
    path('salt_signup', views.salt_signup, name=  'salt_sinup'),
    path('salt_signin', views.salt_signin, name = 'salt_signin'),
    path('preventBrutefoceCheckusername', views.prevBrutefoceCheckusername, name = 'preventBrutefoceCheckusername'),
    path('preventBrutefoce', views.prevBrutefoce, name= 'preventBrutefoce')
]


urlpatterns += static.static(settings.CSS_PASSWORD_URL, document_root = settings.CSS__PASSWORD_ROOT)
urlpatterns += static.static(settings.JS_PASSWORD_URL, document_root = settings.JS_PASSWORD_ROOT)

ATDL/password/models.py
from django.db import models



class User(models.Model):
    ID_user = models.AutoField(primary_key=True)
    user_name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

class LoginLogSection(models.Model):
    ID_section = models.AutoField(primary_key=True)
    ID_user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False) #trang thai login thanh cong hay that bai

class LoginSection(models.Model):
    ID_section = models.ForeignKey(LoginLogSection, on_delete=models.CASCADE, related_name='loginsection')
    challen_num = models.CharField(max_length=10) #so thach thuc
    login_time = models.DateTimeField() #thoi gian phien
    login_false = models.CharField(max_length=10) #so lan sai lien tuc\\


# Create your models here.
class UserSalt(models.Model):
    us_IDuser = models.AutoField(primary_key= True)
    us_username = models.CharField(max_length=100)
    us_password = models.CharField(max_length=100)
    us_salt = models.CharField(max_length=50)
    us_lock = models.BooleanField(default= False)


class UserSaltSection(models.Model):
    uss_IDsection = models.AutoField(primary_key= True)
    uss_IDuser = models.ForeignKey(UserSalt, on_delete=models.CASCADE)
    uss_fistTime = models.DateTimeField()
    uss_status = models.BooleanField(default= False)

class Section(models.Model):
    s_IDsection = models.ForeignKey(UserSaltSection, on_delete= models.CASCADE, related_name = 'usersaltsection')
    s_FalseTimes = models.CharField(max_length=10, default= 0)
    s_lastTime = models.DateTimeField()

ATDL/password/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100)
    password = forms.CharField(label='Password', max_length=100)
    confirmPassword = forms.CharField(label= "Confirm password", max_length= 100)

class Login(forms.Form):
    username =  forms.CharField(label="Username", max_length= 100)
    password = forms.CharField(label="Password", max_length= 100)
class UserForm(forms.Form):
    chal_username = forms.CharField(label='Username', max_length= 100)

class ChallengeForm(forms.Form):
    chal_password = forms.CharField(label='Password', max_length=100, required=False)
    serverChalNum = forms.CharField(label='Mã xác nhận', max_length=100, required=False)

class User(forms.Form):
    username = forms.CharField(max_length =100, label='username')

class Password(forms.Form):
    password = forms.CharField(max_length= 100, label='password')

ATDL/password/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from . import forms
from django.http import JsonResponse
from .static.core.passwordUtilities import password
from .models import LoginLogSection, LoginSection, User, UserSalt, UserSaltSection, Section
import random
import datetime
import hashlib
# Create your views here.
def index(request):
    registerForm = forms.RegisterForm()
    userForm = forms.UserForm()
    challForm = forms.ChallengeForm()
    #them muoi
    signup = forms.RegisterForm()
    signin = forms.Login()
    #bruteforce
    userBF = forms.User()
    pwdBF = forms.Password()
    contex = {'form_mk_basic': registerForm, 'form_user' : userForm, 'form_loginChall': challForm, 'form_signup_salt': signup, 'form_signin_salt': signin, 'form_bruteforce_user': userBF, 'form_bruteforce_pwd': pwdBF}
    return TemplateResponse(request, 'base.html', contex)

def checkAnderson(request):
    data = {}
    if request.method == "POST":
        # tinh toan anderson
        pwd = request.POST.get('password')
        mypass = password.Password(pwd)
        mypass.checkPassword()
        data = {'Mật khẩu': pwd, 'Độ dài': mypass.lenght, 'Xác suất Anderson': mypass.andersonP, 'Độ mạnh yếu': mypass.nhan}
        return JsonResponse(data)
    else:
        return JsonResponse({'err':'false'})

def userRequest(request):
    data = {}
    if request.method == "GET":
        userName = request.GET.get('chal_username')
        queryResult = User.objects.filter(user_name = userName)
        if len(queryResult) == 1:
            userID = getattr(queryResult[0], 'ID_user')
            print(queryResult.values())
            #tao so r ngau nhien luu vao csdl login va gui cho user
            challengeNumber = random.randint(1000,9999)
            #luu section vao loginlogsection
            logsection = LoginLogSection(ID_user = User.objects.get(ID_user = userID), status = False)
            logsection.save()
            #luu section vao loginsesstion
            login_section = LoginSection(ID_section = logsection, challen_num = challengeNumber, login_time = datetime.datetime.now(), login_false = 0)
            login_section.save()
            print('section', getattr(logsection,'ID_section'))
            data = {'statusCode': 200, 'user': userName, 'challenge_number': challengeNumber, 'sectionID': getattr(logsection,'ID_section')}
        else:
            data = {'statusCode': 401,'error': 'user name does not exist'}
    else:
        data ={'statusCode': 405, 'error': 'unknow error'}
    return JsonResponse(data)

def challengeResponse(request):
    if request.method == 'POST':
        sectionID = request.POST.get('sectionID')
        hashpassword = request.POST.get('hashpassword')
        logsection = LoginLogSection.objects.filter(ID_section = sectionID)
        if len(logsection) == 1:
            logsection = logsection[0]
            user = logsection.ID_user
            section = logsection.loginsection.all()[0]
            print(user.password + section.challen_num)
            passwordReal = hashlib.md5((user.password + section.challen_num).encode('utf-8')).hexdigest()
            if str(passwordReal) == hashpassword:
                logsection.status = True
                logsection.save()
                return JsonResponse({"statusCode": 200, 'mess': 'Đăng nhập thàn công'})
            else:
                return JsonResponse({'statusCode': 401, 'mess': 'Sai mật khẩu hoặc mã xác nhận'})
        else:
            return JsonResponse({"error":'something wrongs'})
    return JsonResponse({})

def salt_signup(request):
    data = {}
    if request.method == "POST":
        username_post = request.POST.get('username')
        #check username is not exits
        queryResult = UserSalt.objects.filter(us_username= username_post)
        if len(queryResult) == 0:
            pwd_post = request.POST.get('password')
            pwd = password.Password(pwd_post)
            pwd.themmuoi()
            pwd.hashMD5()
            usersalt = UserSalt.objects.create(us_username= username_post, us_password = pwd.md5, us_salt = pwd.salt)
            data ={'statusCode': 200, 'mess': 'Đăng kí thành công'}
        else:
            data = {'statucCode': 401, 'mess': 'Tài khoản đã tồn tại'}
    else:
        data ={'statusCode': 400, 'mess': 'Lỗi đăng kí'}
    return JsonResponse(data)

def salt_signin(request):
    data = {}
    if request.method == "POST":
        username_post = request.POST.get('username')
        # check username is not exits
        queryResult = UserSalt.objects.filter(us_username=username_post)
        if len(queryResult) == 1:
            user = queryResult[0]
            pwd_post = request.POST.get('password')
            pwd = pwd_post + user.us_salt
            mypwd = password.Password(pwd)
            mypwd.hashMD5()
            if mypwd.md5 == user.us_password:
                mypwd.checkPassword()
                anderson = {'Mật khẩu + salt lưu trong CSDL': pwd, 'Độ dài': mypwd.lenght, 'Xác suất Anderson': mypwd.andersonP,
                        'Độ mạnh yếu': mypwd.nhan}
                data = {'statusCode': 200, 'mess': 'Đăng nhập thành công', 'pwdProperties': anderson}
            else:
                data = {'statucCode': 401, 'mess': 'Sai mật khẩu'}
        else:
            data = {'statucCode': 401, 'mess': 'Tài khoản không tồn tại'}
    else:
        data = {'statusCode': 400, 'mess': 'Lỗi đăng kí'}
    return JsonResponse(data)

def prevBrutefoceCheckusername(request):
    data = {}
    if request.method == 'POST':
        username_post = request.POST.get('username')
        queryResult = UserSalt.objects.filter(us_username=username_post)
        if len(queryResult) == 1:
            user = queryResult[0]
            #tao section
            section = UserSaltSection(uss_IDuser = user, uss_status = False, uss_fistTime = datetime.datetime.now(datetime.timezone.utc))
            section.save()
            sectionInfo = Section(s_IDsection = section, s_FalseTimes = 0, s_lastTime = datetime.datetime.now(datetime.timezone.utc))
            sectionInfo.save()
            data = {'statusCode': 200, 'mess': 'Mời nhập mật khẩu', 'sectionID': section.uss_IDsection}
        else:
            data = {'statusCode': 401, 'mess': 'Tài khoản không tồn tại'}
    return JsonResponse(data)

def prevBrutefoce(request):
    data = {}
    if request.method == 'POST':
        pwd_post = request.POST.get('password')
        section_post = request.POST.get('sectionID')
        querry = UserSaltSection.objects.filter(uss_IDsection = section_post)
        if(len(querry) == 1):
            section = UserSaltSection.objects.get(uss_IDsection = section_post)
            user = section.uss_IDuser
            sectionInfo = section.usersaltsection.all()[0]
            if sectionInfo.s_FalseTimes == 5:
                user.us_lock == True
                user.save()
            #check password
            if section.uss_status == False:
                lastTime = sectionInfo.s_lastTime
                fistTime = section.uss_fistTime
                #tinh thoi gian phat:
                falseTimes = int(sectionInfo.s_FalseTimes)
                waitPentime = falseTimes * 2
                penaltyTime = lastTime + datetime.timedelta(seconds= falseTimes * 2)
                if datetime.datetime.now(datetime.timezone.utc) < penaltyTime:
                    data = {'statusCode': 402, 'mess': 'Bạn phải đợi hết thời gian', 'penaltyTime':penaltyTime.time(), 'mustwait': waitPentime}
                else:
                    mypwd = password.Password(pwd_post + user.us_salt)
                    mypwd.hashMD5()
                    if mypwd.md5 == user.us_password:
                        section.uss_status = True
                        section.save()
                        data = {'statusCode': 200, 'mess': 'Đăng nhập thành công'}
                    else:
                        data = {'statusCode': 401, 'mess': 'Sai mật khẩu'}
                        sectionInfo.s_FalseTimes = int(sectionInfo.s_FalseTimes) + 1
                        sectionInfo.s_lastTime = datetime.datetime.now(datetime.timezone.utc)
                        sectionInfo.save()
            else:
                data = {'statusCode': 401, 'mess': 'section out of date'}
    else:   data = {'statusCode': 500, 'mess': 'co loi'}
    return JsonResponse(data)

ATDL/password/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{'/password/css/style.css'}}">
    <script  type="text/javascript" src="{{'/password/js/jquery-3.4.1.min.js'}}"></script>
    <script  type="text/javascript" src="{{'/password/js/md5.min.js'}}"></script>
    <title>ATDL_XacThuc</title>

</head>
<body>
    <h1> Xác thực mật khẩu </h1>
    <section class="anderson">
        <div>
            <h3 id = 'header_1'>Kiểm tra mật khẩu với công thức anderson</h3>
            <form id = 'form_1'>
                {% csrf_token %} 
                {{form_mk_basic}}
                <input type = 'submit' value="Check Anderson">
            </form>
        </div>
        <div id = 'andersonRes'></div>
        <script>
                $(document).ready(function(){
                    var user = $('#form_1 input[name=username]');
                    var confpwd = $('#form_1 input[name = confirmPassword]');
                    user.prop('required', false);
                    confpwd.prop('required', false);
                    // user.prop('class', 'hide');
                    // confpwd.prop('class', 'hide');
                    
                   

                    $('#form_1').on('submit', function(e){
                        e.preventDefault();
                        e.stopPropagation();
                        $.ajax({
                            type: "POST",
                            url: "checkAnderson",
                            data: $('#form_1').serialize(),
                            dataType:'json',
                            success: function(data){
                                console.log(data);
                                // $('#andersonRes').html(JSON.stringify(data));
                                var tabletemp;
                                Object.keys(data).forEach(function(key) {
                                    tabletemp += '<tr><td>' + key +'</td><td>' + data[key] +'</td></tr>';
                                // console.table('Key : ' + key + ', Value : ' + data[key]);
                                })
                                $('#andersonRes').html(tabletemp);
                            },  
                            
                        })
                    })
                })
        
            </script>
    </section>
 <section>
<!-- THACH THU DAP UNG Challenge response -->
        <h3>Thách thức đáp ứng</h3>

        <form action="" id='checkuser'>
            {% csrf_token %}
            {{form_user}}   
           <input type="submit" name="" value="Login">
        </form>
        <div id="serverChallengeNumber" ></div>

        <form action="" id ='login_chall_res'>
            {% csrf_token %}
            {{form_loginChall}}
            <input type="submit" name="" id="Login">
        </form>
        
    </div>
    <script>
        $(document).ready(function(){
            var form = $('#checkuser');
            var sectionID;
            var formLogin = $('#login_chall_res');
            // hide password and numver filed before check username
            formLogin.hide();
            form.on('submit',function(e){
                username = $('#id_chal_username').val();
                e.preventDefault();
                e.stopPropagation();
                console.log('submit');
                $.ajax({
                type: "GET",
                url: 'requestLogin',
                dataType: 'json',
                data: form.serialize(),
                success: function(data){
                    console.log(data);
                    console.log();
                    // show login form if user is exist
                    var status = data['statusCode'];
                    console.log(status);
                    if(status === 200){
                        $('#serverChallengeNumber').html("Mã xác nhận của bạn là: " + data['challenge_number']);
                        $('#login_chall_res').show();
                        $('#checkuser').hide();
                        sectionID = data['sectionID'];
                    }
                    else{
                        $('#serverChallengeNumber').html('Sai tài khoản');
                    }
                 },
                error: function(data){
                   
                }
                })
            })

            
            formLogin.on('submit', function(e){
                e.preventDefault();
                var password = $('#id_chal_password').val();
                var chalNum = $('#id_serverChalNum').val();
                var hashval = password + chalNum ;
                hashval = md5(hashval);
                console.log(hashval);
                $.ajax({
                    type: 'POST',
                    url: 'challengeResponse',
                    dataType: 'json',
                    data:{
                        sectionID: sectionID,                        
                        hashpassword: hashval,
                        csrfmiddlewaretoken:  $('input[ name = csrfmiddlewaretoken]').val(),
                    },
                    success : function(data){
                        console.log(data);
                        alert(data['mess']);
                    }
                })           
               

            })
        })
</script>
</section> 
<!-- THACH THU DAP UNG Challenge response -->
  
<section>
<!-- Thêm muối vào mật khẩu -->
<h3>Thêm muối vào mật khẩu</h3>
<p>Mô tả: Đăng kí tài khoản, mật khẩu lưu trong CSDL dưới dạng pasword + salt <br>
    salt: Sinh ra ngẫu nhiên lưu trong CSDL với template (2char + '_' + 2digit)
</p>
<h4> Đăng kí</h4>
<form id="f_signup">
    {% csrf_token %}
    {{form_signup_salt}}
    <input type="submit" name="" id="" value="Sign Up">
</form>
<div id = 'a123'></div>
<h4>Đăng nhập và trả về các thuộc tính theo công thức anderson</h4>
<form action="" id=f_signin>
    {% csrf_token %}
    {{form_signin_salt}}
    <input type="submit" name="" id="" value="Sin In">
</form>
<div id = 'anderson_salt'>

</div>

<script>
$(document).ready(function(){
    //sign up
    $('#f_signup').on('submit',function(e){
        e.preventDefault();
        e.stopPropagation();
        var pwd = $('#f_signup input[name =password]').val();
        var confirmPwd = $('#f_signup input[name =confirmPassword]').val();
        if(pwd != confirmPwd){
            alert('Password and confirm password does not match!');
        }
        else {
            $.ajax({
                type : 'POST',
                url: 'salt_signup',
                dataType: 'json',
                data: $('#f_signup').serialize(),
                success: function(data){
                    console.log(data);
                    alert(data['mess']);  
                  
                }
                
            })
        }
    })
    //------------------------------------------------
    //sign in
    $('#f_signin').on('submit', function(e){
        e.preventDefault();
        e.stopPropagation();
        $.ajax({
            type : 'POST',
                url: 'salt_signin',
                dataType: 'json',
                data: $('#f_signin').serialize(),
                success: function(data){
                    console.log(data);
                    alert(data['mess']);
                    if(data['statusCode'] == 200){
                        var properties = data['pwdProperties'];
                        var tabletemp;
                                Object.keys(properties).forEach(function(key) {
                                    tabletemp += '<tr><td>' + key +'</td><td>' + properties[key] +'</td></tr>';
                                // console.table('Key : ' + key + ', Value : ' + data[key]);
                                })
                                $('#anderson_salt').html(tabletemp);
                    }
                }
        })
    })


})
</script>
</section>

<section>
    <!-- Hạn chế bruteforce bằng cách phạt thời gian nếu đăng nhập sai -->
    <h3>Hạn chế bruteforce</h3>
    <form action="" id='checkusernameBF'>
        {% csrf_token %}
        {{form_bruteforce_user}}
        <input type="submit" name="" id="" value="Login">   
    </form>
    <div id = 'bfUserMess'>

    </div>
    <form action="" id='loginBF'>
            {% csrf_token %}
            {{form_bruteforce_pwd}}
            <input type="submit" name="" id="bfLoginSubmit" value="Login">   
     </form>
     <div id = 'bfLogin'></div>
     <div id = 'countdown'></div>
     <div>
         <p><br><br><br></p>
     </div>

    <script>
        $(document).ready(function(){
            var sectionID;
            $('#loginBF').hide();
            $('#checkusernameBF').on('submit', function(e){

                e.preventDefault();
                e.stopPropagation();

                $.ajax({
                    type: 'POST',
                    url: 'preventBrutefoceCheckusername',
                    dataType: 'json',
                    data: $('#checkusernameBF').serialize(),
                    success: function(data){
                        $('#bfUserMess').html(data['mess']);
                        sectionID = data['sectionID'];
                        console.log( data['sectionID']);
                        
                        if (data['statusCode'] == 200) {
                            $('#checkusernameBF').hide();
                            $('#loginBF').show();
                            }

                    }
                })

            })

        
        $('#loginBF').on('submit', function(e){
            e.preventDefault();
                e.stopPropagation();
                $('#bfLogin').show();
                $('#countdown').show();
                $.ajax({
                    type: 'POST',
                    url: 'preventBrutefoce',
                    dataType: 'json',
                    data:{
                        sectionID: sectionID,                        
                        password:  $('#loginBF input[name = password]').val(),
                        csrfmiddlewaretoken:  $('#loginBF input[ name = csrfmiddlewaretoken]').val(),                      
                    },
                    success: function(data){
                        console.log(data);
                        var status = data['statusCode']
                        if (status == 402){
                            $('#bfLogin').html('Bạn nhập quá sai quá nhiều lần, vui lòng đợi');
                            var timeLeft = data['mustwait'];
                            var elem = document.getElementById('countdown');
                            var timerId = setInterval(countdown, 1000);
                            $('#bfLoginSubmit').prop( "disabled", true );
                            function countdown() {
                                if (timeLeft == -1) {
                                    clearTimeout(timerId);
                                    $('#bfLoginSubmit').prop( "disabled", false );
                                    $('#countdown').hide();
                                    $('#bfLogin').hide();
                                } else {
                                    elem.innerHTML = timeLeft + 'seconds remaining';
                                    timeLeft--;
                                }
                            }
                        }
                        else {
                            $('#bfLogin').html(data['mess']);
                            $('#countdown').hide();
                        }
                    }
                })
                console.log(sectionID);
            })
        })
    </script>
</section>
</body>
</html>

ATDL/password/templates/challengeAuth.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Challenge</title>
</head>
<body>
    <h3>

    </h3>
</body>
</html>